### PR TITLE
♻️ refactor presence channel un/subscription events, add pusher:member_removed event

### PR DESCRIPTION
**Pull request by mayteio**
Hey, this PR further tweaks and refactors subscription/unsubscription events.
- moved events to their own file, pusherEvents
- added member:removed event
- updated unsubscribe to only remove own callbacks, so if other clients are 'connected' theirs stay intact
- added reset method to the pusher instance, so each test can begin with a clean slate
- resolved conflicts with the master branch

### CODE REVIEW

**Comment by nikolalsvk** [comment]
Hey, @mayteio! Thanks so much for this! Everything looks good to me 👍 

Does it make sense to add new usage examples for `pusher:member_removed` event?

**Comment by mayteio** [comment]
Potentially yes. I’m on holiday without a laptop, I can get to it when I’m back.

**Comment by nikolalsvk** [comment]
Sure @mayteio, no rush, enjoy your holiday 🌴

**Comment by mayteio** [comment]
Hey @nikolalsvk, thanks for your patience. I have added usage information under the presence channels header. I also added a test case in the example to demonstrate.

**Comment by nikolalsvk** [comment]
Thank you @mayteio! You are the best 🍰

**Comment by nikolalsvk** [comment]
Just released this, sorry for the wait 🙇 https://github.com/nikolalsvk/pusher-js-mock/releases/tag/0.3.1

**Pull request merged**
